//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonSDK.JuyJuka.QuickMapStart {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Form1Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Form1Settings defaultInstance = ((Form1Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Form1Settings())));
        
        public static Form1Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
